### ISSUE TITLE
Provide an option for Pifile inheritance

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pimod#7]
As an addition to the FROM definition I suggest to introduce an PARENT statement.

When a Pifile stars with an PARENT statement, pimod first creates the image defined in the parent Pifile and afterwards continues executing the Pifile.

**Comment by gh0st42** [comment]
Mmmh... something smells like docker ;)
Isn't it enough to reference your previously generated image in FROM? Otherwise one could just source another Pifile in the beginning. Should work, shouldn't it?
If intermediate images are a thing then setting a temporary working directory for image generation might also be a good idea..

**Comment by jonashoechst** [comment]
Actually either using a Base Image with `FROM` or `source` of another Pifile are two options that work just fine for me. In my opinion this possibilities should be documented.
